<?php
    $countryArray = array(
        'AD'=>array('key' => 'AD','name'=>'ANDORRA','code'=>'376'),
        'AE'=>array('key' => 'AE','name'=>'UNITED ARAB EMIRATES','code'=>'971'),
        'AF'=>array('key' => 'AF','name'=>'AFGHANISTAN','code'=>'93'),
        'AG'=>array('key' => 'AG','name'=>'ANTIGUA AND BARBUDA','code'=>'1268'),
        'AI'=>array('key' => 'AI','name'=>'ANGUILLA','code'=>'1264'),
        'AL'=>array('key' => 'AL','name'=>'ALBANIA','code'=>'355'),
        'AM'=>array('key' => 'AM','name'=>'ARMENIA','code'=>'374'),
        'AN'=>array('key' => 'AN','name'=>'NETHERLANDS ANTILLES','code'=>'599'),
        'AO'=>array('key' => 'AO','name'=>'ANGOLA','code'=>'244'),
        'AQ'=>array('key' => 'AQ','name'=>'ANTARCTICA','code'=>'672'),
        'AR'=>array('key' => 'AR','name'=>'ARGENTINA','code'=>'54'),
        'AS'=>array('key' => 'AS','name'=>'AMERICAN SAMOA','code'=>'1684'),
        'AT'=>array('key' => 'AT','name'=>'AUSTRIA','code'=>'43'),
        'AU'=>array('key' => 'AU','name'=>'AUSTRALIA','code'=>'61'),
        'AW'=>array('key' => 'AW','name'=>'ARUBA','code'=>'297'),
        'AZ'=>array('key' => 'AZ','name'=>'AZERBAIJAN','code'=>'994'),
        'BA'=>array('key' => 'BA','name'=>'BOSNIA AND HERZEGOVINA','code'=>'387'),
        'BB'=>array('key' => 'BB','name'=>'BARBADOS','code'=>'1246'),
        'BD'=>array('key' => 'BD','name'=>'BANGLADESH','code'=>'880'),
        'BE'=>array('key' => 'BE','name'=>'BELGIUM','code'=>'32'),
        'BF'=>array('key' => 'BF','name'=>'BURKINA FASO','code'=>'226'),
        'BG'=>array('key' => 'BG','name'=>'BULGARIA','code'=>'359'),
        'BH'=>array('key' => 'BH','name'=>'BAHRAIN','code'=>'973'),
        'BI'=>array('key' => 'BI','name'=>'BURUNDI','code'=>'257'),
        'BJ'=>array('key' => 'BJ','name'=>'BENIN','code'=>'229'),
        'BL'=>array('key' => 'BL','name'=>'SAINT BARTHELEMY','code'=>'590'),
        'BM'=>array('key' => 'BM','name'=>'BERMUDA','code'=>'1441'),
        'BN'=>array('key' => 'BN','name'=>'BRUNEI DARUSSALAM','code'=>'673'),
        'BO'=>array('key' => 'BO','name'=>'BOLIVIA','code'=>'591'),
        'BR'=>array('key' => 'BR','name'=>'BRAZIL','code'=>'55'),
        'BS'=>array('key' => 'BS','name'=>'BAHAMAS','code'=>'1242'),
        'BT'=>array('key' => 'BT','name'=>'BHUTAN','code'=>'975'),
        'BW'=>array('key' => 'BW','name'=>'BOTSWANA','code'=>'267'),
        'BY'=>array('key' => 'BY','name'=>'BELARUS','code'=>'375'),
        'BZ'=>array('key' => 'BZ','name'=>'BELIZE','code'=>'501'),
        'CA'=>array('key' => 'CA','name'=>'CANADA','code'=>'1'),
        'CC'=>array('key' => 'CC','name'=>'COCOS (KEELING) ISLANDS','code'=>'61'),
        'CD'=>array('key' => 'CD','name'=>'CONGO, THE DEMOCRATIC REPUBLIC OF THE','code'=>'243'),
        'CF'=>array('key' => 'CF','name'=>'CENTRAL AFRICAN REPUBLIC','code'=>'236'),
        'CG'=>array('key' => 'CG','name'=>'CONGO','code'=>'242'),
        'CH'=>array('key' => 'CH','name'=>'SWITZERLAND','code'=>'41'),
        'CI'=>array('key' => 'CI','name'=>'COTE D IVOIRE','code'=>'225'),
        'CK'=>array('key' => 'CK','name'=>'COOK ISLANDS','code'=>'682'),
        'CL'=>array('key' => 'CL','name'=>'CHILE','code'=>'56'),
        'CM'=>array('key' => 'CM','name'=>'CAMEROON','code'=>'237'),
        'CN'=>array('key' => 'CN','name'=>'CHINA','code'=>'86'),
        'CO'=>array('key' => 'CO','name'=>'COLOMBIA','code'=>'57'),
        'CR'=>array('key' => 'CR','name'=>'COSTA RICA','code'=>'506'),
        'CU'=>array('key' => 'CU','name'=>'CUBA','code'=>'53'),
        'CV'=>array('key' => 'CV','name'=>'CAPE VERDE','code'=>'238'),
        'CX'=>array('key' => 'CX','name'=>'CHRISTMAS ISLAND','code'=>'61'),
        'CY'=>array('key' => 'CY','name'=>'CYPRUS','code'=>'357'),
        'CZ'=>array('key' => 'CZ','name'=>'CZECH REPUBLIC','code'=>'420'),
        'DE'=>array('key' => 'DE','name'=>'GERMANY','code'=>'49'),
        'DJ'=>array('key' => 'DJ','name'=>'DJIBOUTI','code'=>'253'),
        'DK'=>array('key' => 'DK','name'=>'DENMARK','code'=>'45'),
        'DM'=>array('key' => 'DM','name'=>'DOMINICA','code'=>'1767'),
        'DO'=>array('key' => 'DO','name'=>'DOMINICAN REPUBLIC','code'=>'1809'),
        'DZ'=>array('key' => 'DZ','name'=>'ALGERIA','code'=>'213'),
        'EC'=>array('key' => 'EC','name'=>'ECUADOR','code'=>'593'),
        'EE'=>array('key' => 'EE','name'=>'ESTONIA','code'=>'372'),
        'EG'=>array('key' => 'EG','name'=>'EGYPT','code'=>'20'),
        'ER'=>array('key' => 'ER','name'=>'ERITREA','code'=>'291'),
        'ES'=>array('key' => 'ES','name'=>'SPAIN','code'=>'34'),
        'ET'=>array('key' => 'ET','name'=>'ETHIOPIA','code'=>'251'),
        'FI'=>array('key' => 'FI','name'=>'FINLAND','code'=>'358'),
        'FJ'=>array('key' => 'FJ','name'=>'FIJI','code'=>'679'),
        'FK'=>array('key' => 'FK','name'=>'FALKLAND ISLANDS (MALVINAS)','code'=>'500'),
        'FM'=>array('key' => 'FM','name'=>'MICRONESIA, FEDERATED STATES OF','code'=>'691'),
        'FO'=>array('key' => 'FO','name'=>'FAROE ISLANDS','code'=>'298'),
        'FR'=>array('key' => 'FR','name'=>'FRANCE','code'=>'33'),
        'GA'=>array('key' => 'GA','name'=>'GABON','code'=>'241'),
        'GB'=>array('key' => 'GB','name'=>'UNITED KINGDOM','code'=>'44'),
        'GD'=>array('key' => 'GD','name'=>'GRENADA','code'=>'1473'),
        'GE'=>array('key' => 'GE','name'=>'GEORGIA','code'=>'995'),
        'GH'=>array('key' => 'GH','name'=>'GHANA','code'=>'233'),
        'GI'=>array('key' => 'GI','name'=>'GIBRALTAR','code'=>'350'),
        'GL'=>array('key' => 'GL','name'=>'GREENLAND','code'=>'299'),
        'GM'=>array('key' => 'GM','name'=>'GAMBIA','code'=>'220'),
        'GN'=>array('key' => 'GN','name'=>'GUINEA','code'=>'224'),
        'GQ'=>array('key' => 'GQ','name'=>'EQUATORIAL GUINEA','code'=>'240'),
        'GR'=>array('key' => 'GR','name'=>'GREECE','code'=>'30'),
        'GT'=>array('key' => 'GT','name'=>'GUATEMALA','code'=>'502'),
        'GU'=>array('key' => 'GU','name'=>'GUAM','code'=>'1671'),
        'GW'=>array('key' => 'GW','name'=>'GUINEA-BISSAU','code'=>'245'),
        'GY'=>array('key' => 'GY','name'=>'GUYANA','code'=>'592'),
        'HK'=>array('key' => 'HK','name'=>'HONG KONG','code'=>'852'),
        'HN'=>array('key' => 'HN','name'=>'HONDURAS','code'=>'504'),
        'HR'=>array('key' => 'HR','name'=>'CROATIA','code'=>'385'),
        'HT'=>array('key' => 'HT','name'=>'HAITI','code'=>'509'),
        'HU'=>array('key' => 'HU','name'=>'HUNGARY','code'=>'36'),
        'ID'=>array('key' => 'ID','name'=>'INDONESIA','code'=>'62'),
        'IE'=>array('key' => 'IE','name'=>'IRELAND','code'=>'353'),
        'IL'=>array('key' => 'IL','name'=>'ISRAEL','code'=>'972'),
        'IM'=>array('key' => 'IM','name'=>'ISLE OF MAN','code'=>'44'),
        'IN'=>array('key' => 'IN','name'=>'INDIA','code'=>'91'),
        'IQ'=>array('key' => 'IQ','name'=>'IRAQ','code'=>'964'),
        'IR'=>array('key' => 'IR','name'=>'IRAN, ISLAMIC REPUBLIC OF','code'=>'98'),
        'IS'=>array('key' => 'IS','name'=>'ICELAND','code'=>'354'),
        'IT'=>array('key' => 'IT','name'=>'ITALY','code'=>'39'),
        'JM'=>array('key' => 'JM','name'=>'JAMAICA','code'=>'1876'),
        'JO'=>array('key' => 'JO','name'=>'JORDAN','code'=>'962'),
        'JP'=>array('key' => 'JP','name'=>'JAPAN','code'=>'81'),
        'KE'=>array('key' => 'KE','name'=>'KENYA','code'=>'254'),
        'KG'=>array('key' => 'KG','name'=>'KYRGYZSTAN','code'=>'996'),
        'KH'=>array('key' => 'KH','name'=>'CAMBODIA','code'=>'855'),
        'KI'=>array('key' => 'KI','name'=>'KIRIBATI','code'=>'686'),
        'KM'=>array('key' => 'KM','name'=>'COMOROS','code'=>'269'),
        'KN'=>array('key' => 'KN','name'=>'SAINT KITTS AND NEVIS','code'=>'1869'),
        'KP'=>array('key' => 'KP','name'=>'KOREA DEMOCRATIC PEOPLES REPUBLIC OF','code'=>'850'),
        'KR'=>array('key' => 'KR','name'=>'KOREA REPUBLIC OF','code'=>'82'),
        'KW'=>array('key' => 'KW','name'=>'KUWAIT','code'=>'965'),
        'KY'=>array('key' => 'KY','name'=>'CAYMAN ISLANDS','code'=>'1345'),
        'KZ'=>array('key' => 'KZ','name'=>'KAZAKSTAN','code'=>'7'),
        'LA'=>array('key' => 'LA','name'=>'LAO PEOPLES DEMOCRATIC REPUBLIC','code'=>'856'),
        'LB'=>array('key' => 'LB','name'=>'LEBANON','code'=>'961'),
        'LC'=>array('key' => 'LC','name'=>'SAINT LUCIA','code'=>'1758'),
        'LI'=>array('key' => 'LI','name'=>'LIECHTENSTEIN','code'=>'423'),
        'LK'=>array('key' => 'LK','name'=>'SRI LANKA','code'=>'94'),
        'LR'=>array('key' => 'LR','name'=>'LIBERIA','code'=>'231'),
        'LS'=>array('key' => 'LS','name'=>'LESOTHO','code'=>'266'),
        'LT'=>array('key' => 'LT','name'=>'LITHUANIA','code'=>'370'),
        'LU'=>array('key' => 'LU','name'=>'LUXEMBOURG','code'=>'352'),
        'LV'=>array('key' => 'LV','name'=>'LATVIA','code'=>'371'),
        'LY'=>array('key' => 'LY','name'=>'LIBYAN ARAB JAMAHIRIYA','code'=>'218'),
        'MA'=>array('key' => 'MA','name'=>'MOROCCO','code'=>'212'),
        'MC'=>array('key' => 'MC','name'=>'MONACO','code'=>'377'),
        'MD'=>array('key' => 'MD','name'=>'MOLDOVA, REPUBLIC OF','code'=>'373'),
        'ME'=>array('key' => 'ME','name'=>'MONTENEGRO','code'=>'382'),
        'MF'=>array('key' => 'MF','name'=>'SAINT MARTIN','code'=>'1599'),
        'MG'=>array('key' => 'MG','name'=>'MADAGASCAR','code'=>'261'),
        'MH'=>array('key' => 'MH','name'=>'MARSHALL ISLANDS','code'=>'692'),
        'MK'=>array('key' => 'MK','name'=>'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','code'=>'389'),
        'ML'=>array('key' => 'ML','name'=>'MALI','code'=>'223'),
        'MM'=>array('key' => 'MM','name'=>'MYANMAR','code'=>'95'),
        'MN'=>array('key' => 'MN','name'=>'MONGOLIA','code'=>'976'),
        'MO'=>array('key' => 'MO','name'=>'MACAU','code'=>'853'),
        'MP'=>array('key' => 'MP','name'=>'NORTHERN MARIANA ISLANDS','code'=>'1670'),
        'MR'=>array('key' => 'MR','name'=>'MAURITANIA','code'=>'222'),
        'MS'=>array('key' => 'MS','name'=>'MONTSERRAT','code'=>'1664'),
        'MT'=>array('key' => 'MT','name'=>'MALTA','code'=>'356'),
        'MU'=>array('key' => 'MU','name'=>'MAURITIUS','code'=>'230'),
        'MV'=>array('key' => 'MV','name'=>'MALDIVES','code'=>'960'),
        'MW'=>array('key' => 'MW','name'=>'MALAWI','code'=>'265'),
        'MX'=>array('key' => 'MX','name'=>'MEXICO','code'=>'52'),
        'MY'=>array('key' => 'MY','name'=>'MALAYSIA','code'=>'60'),
        'MZ'=>array('key' => 'MZ','name'=>'MOZAMBIQUE','code'=>'258'),
        'NA'=>array('key' => 'NA','name'=>'NAMIBIA','code'=>'264'),
        'NC'=>array('key' => 'NC','name'=>'NEW CALEDONIA','code'=>'687'),
        'NE'=>array('key' => 'NE','name'=>'NIGER','code'=>'227'),
        'NG'=>array('key' => 'NG','name'=>'NIGERIA','code'=>'234'),
        'NI'=>array('key' => 'NI','name'=>'NICARAGUA','code'=>'505'),
        'NL'=>array('key' => 'NL','name'=>'NETHERLANDS','code'=>'31'),
        'NO'=>array('key' => 'NO','name'=>'NORWAY','code'=>'47'),
        'NP'=>array('key' => 'NP','name'=>'NEPAL','code'=>'977'),
        'NR'=>array('key' => 'NR','name'=>'NAURU','code'=>'674'),
        'NU'=>array('key' => 'NU','name'=>'NIUE','code'=>'683'),
        'NZ'=>array('key' => 'NZ','name'=>'NEW ZEALAND','code'=>'64'),
        'OM'=>array('key' => 'OM','name'=>'OMAN','code'=>'968'),
        'PA'=>array('key' => 'PA','name'=>'PANAMA','code'=>'507'),
        'PE'=>array('key' => 'PE','name'=>'PERU','code'=>'51'),
        'PF'=>array('key' => 'PF','name'=>'FRENCH POLYNESIA','code'=>'689'),
        'PG'=>array('key' => 'PG','name'=>'PAPUA NEW GUINEA','code'=>'675'),
        'PH'=>array('key' => 'PH','name'=>'PHILIPPINES','code'=>'63'),
        'PK'=>array('key' => 'PK','name'=>'PAKISTAN','code'=>'92'),
        'PL'=>array('key' => 'PL','name'=>'POLAND','code'=>'48'),
        'PM'=>array('key' => 'PM','name'=>'SAINT PIERRE AND MIQUELON','code'=>'508'),
        'PN'=>array('key' => 'PN','name'=>'PITCAIRN','code'=>'870'),
        'PR'=>array('key' => 'PR','name'=>'PUERTO RICO','code'=>'1'),
        'PT'=>array('key' => 'PT','name'=>'PORTUGAL','code'=>'351'),
        'PW'=>array('key' => 'PW','name'=>'PALAU','code'=>'680'),
        'PY'=>array('key' => 'PY','name'=>'PARAGUAY','code'=>'595'),
        'QA'=>array('key' => 'QA','name'=>'QATAR','code'=>'974'),
        'RO'=>array('key' => 'RO','name'=>'ROMANIA','code'=>'40'),
        'RS'=>array('key' => 'RS','name'=>'SERBIA','code'=>'381'),
        'RU'=>array('key' => 'RU','name'=>'RUSSIAN FEDERATION','code'=>'7'),
        'RW'=>array('key' => 'RW','name'=>'RWANDA','code'=>'250'),
        'SA'=>array('key' => 'SA','name'=>'SAUDI ARABIA','code'=>'966'),
        'SB'=>array('key' => 'SB','name'=>'SOLOMON ISLANDS','code'=>'677'),
        'SC'=>array('key' => 'SC','name'=>'SEYCHELLES','code'=>'248'),
        'SD'=>array('key' => 'SD','name'=>'SUDAN','code'=>'249'),
        'SE'=>array('key' => 'SE','name'=>'SWEDEN','code'=>'46'),
        'SG'=>array('key' => 'SG','name'=>'SINGAPORE','code'=>'65'),
        'SH'=>array('key' => 'SH','name'=>'SAINT HELENA','code'=>'290'),
        'SI'=>array('key' => 'SI','name'=>'SLOVENIA','code'=>'386'),
        'SK'=>array('key' => 'SK','name'=>'SLOVAKIA','code'=>'421'),
        'SL'=>array('key' => 'SL','name'=>'SIERRA LEONE','code'=>'232'),
        'SM'=>array('key' => 'SM','name'=>'SAN MARINO','code'=>'378'),
        'SN'=>array('key' => 'SN','name'=>'SENEGAL','code'=>'221'),
        'SO'=>array('key' => 'SO','name'=>'SOMALIA','code'=>'252'),
        'SR'=>array('key' => 'SR','name'=>'SURINAME','code'=>'597'),
        'ST'=>array('key' => 'ST','name'=>'SAO TOME AND PRINCIPE','code'=>'239'),
        'SV'=>array('key' => 'SV','name'=>'EL SALVADOR','code'=>'503'),
        'SY'=>array('key' => 'SY','name'=>'SYRIAN ARAB REPUBLIC','code'=>'963'),
        'SZ'=>array('key' => 'SZ','name'=>'SWAZILAND','code'=>'268'),
        'TC'=>array('key' => 'TC','name'=>'TURKS AND CAICOS ISLANDS','code'=>'1649'),
        'TD'=>array('key' => 'TD','name'=>'CHAD','code'=>'235'),
        'TG'=>array('key' => 'TG','name'=>'TOGO','code'=>'228'),
        'TH'=>array('key' => 'TH','name'=>'THAILAND','code'=>'66'),
        'TJ'=>array('key' => 'TJ','name'=>'TAJIKISTAN','code'=>'992'),
        'TK'=>array('key' => 'TK','name'=>'TOKELAU','code'=>'690'),
        'TL'=>array('key' => 'TL','name'=>'TIMOR-LESTE','code'=>'670'),
        'TM'=>array('key' => 'TM','name'=>'TURKMENISTAN','code'=>'993'),
        'TN'=>array('key' => 'TN','name'=>'TUNISIA','code'=>'216'),
        'TO'=>array('key' => 'TO','name'=>'TONGA','code'=>'676'),
        'TR'=>array('key' => 'TR','name'=>'TURKEY','code'=>'90'),
        'TT'=>array('key' => 'TT','name'=>'TRINIDAD AND TOBAGO','code'=>'1868'),
        'TV'=>array('key' => 'TV','name'=>'TUVALU','code'=>'688'),
        'TW'=>array('key' => 'TW','name'=>'TAIWAN, PROVINCE OF CHINA','code'=>'886'),
        'TZ'=>array('key' => 'TZ','name'=>'TANZANIA, UNITED REPUBLIC OF','code'=>'255'),
        'UA'=>array('key' => 'UA','name'=>'UKRAINE','code'=>'380'),
        'UG'=>array('key' => 'UG','name'=>'UGANDA','code'=>'256'),
        'US'=>array('key' => 'US','name'=>'UNITED STATES','code'=>'1'),
        'UY'=>array('key' => 'UY','name'=>'URUGUAY','code'=>'598'),
        'UZ'=>array('key' => 'UZ','name'=>'UZBEKISTAN','code'=>'998'),
        'VA'=>array('key' => 'VA','name'=>'HOLY SEE (VATICAN CITY STATE)','code'=>'39'),
        'VC'=>array('key' => 'VC','name'=>'SAINT VINCENT AND THE GRENADINES','code'=>'1784'),
        'VE'=>array('key' => 'VE','name'=>'VENEZUELA','code'=>'58'),
        'VG'=>array('key' => 'VG','name'=>'VIRGIN ISLANDS, BRITISH','code'=>'1284'),
        'VI'=>array('key' => 'VI','name'=>'VIRGIN ISLANDS, U.S.','code'=>'1340'),
        'VN'=>array('key' => 'VN','name'=>'VIET NAM','code'=>'84'),
        'VU'=>array('key' => 'VU','name'=>'VANUATU','code'=>'678'),
        'WF'=>array('key' => 'WF','name'=>'WALLIS AND FUTUNA','code'=>'681'),
        'WS'=>array('key' => 'WS','name'=>'SAMOA','code'=>'685'),
        'XK'=>array('key' => 'XK','name'=>'KOSOVO','code'=>'381'),
        'YE'=>array('key' => 'YE','name'=>'YEMEN','code'=>'967'),
        'YT'=>array('key' => 'YT','name'=>'MAYOTTE','code'=>'262'),
        'ZA'=>array('key' => 'ZA','name'=>'SOUTH AFRICA','code'=>'27'),
        'ZM'=>array('key' => 'ZM','name'=>'ZAMBIA','code'=>'260'),
        'ZW'=>array('key' => 'ZW','name'=>'ZIMBABWE','code'=>'263')
    );
    echo "
    <link href='/sis/studios/assets/css/flag-icon.min.css' rel='stylesheet' type='text/css'>
		<style>
			.select2-container{
                width: 100%!important;
			}
			.select2-search--dropdown .select2-search__field {
				width: 98%;
			}	
			.select2-container .select2-selection--single {
				height: 40px !important;
				border-top-right-radius: 0px;
				border-bottom-right-radius: 0px;
				padding-top: 6px;
				border-top-left-radius: 10px;
				border-bottom-left-radius: 10px;
				background-color: transparent;
			}
			.select2-selection__arrow {
				height: 34px !important;
            }
            .select2-container *:focus {
                outline: none;
            }
            .flag-text { margin-left: 10px; }
		</style>
    <script>
    $(function() {
        var isoCountries = [
            {'acronym':'AE','text':'AE +971','l_text':'UNITED ARAB EMIRATES','id':'971'},
            {'acronym':'AF','text':'AF +93','l_text':'AFGHANISTAN','id':'93'},
            {'acronym':'AG','text':'AG +1268','l_text':'ANTIGUA AND BARBUDA','id':'1268'},
            {'acronym':'AI','text':'AI +1264','l_text':'ANGUILLA','id':'1264'},
            {'acronym':'AL','text':'AL +355','l_text':'ALBANIA','id':'355'},
            {'acronym':'AM','text':'AM +374','l_text':'ARMENIA','id':'374'},
            {'acronym':'AO','text':'AO +244','l_text':'ANGOLA','id':'244'},
            {'acronym':'AQ','text':'AQ +672','l_text':'ANTARCTICA','id':'672'},
            {'acronym':'AR','text':'AR +54','l_text':'ARGENTINA','id':'54'},
            {'acronym':'AS','text':'AS +1684','l_text':'AMERICAN SAMOA','id':'1684'},
            {'acronym':'AT','text':'AT +43','l_text':'AUSTRIA','id':'43'},
            {'acronym':'AU','text':'AU +61','l_text':'AUSTRALIA','id':'61'},
            {'acronym':'AW','text':'AW +297','l_text':'ARUBA','id':'297'},
            {'acronym':'AZ','text':'AZ +994','l_text':'AZERBAIJAN','id':'994'},
            {'acronym':'BA','text':'BA +387','l_text':'BOSNIA AND HERZEGOVINA','id':'387'},
            {'acronym':'BB','text':'BB +1246','l_text':'BARBADOS','id':'1246'},
            {'acronym':'BD','text':'BD +880','l_text':'BANGLADESH','id':'880'},
            {'acronym':'BE','text':'BE +32','l_text':'BELGIUM','id':'32'},
            {'acronym':'BF','text':'BF +226','l_text':'BURKINA FASO','id':'226'},
            {'acronym':'BG','text':'BG +359','l_text':'BULGARIA','id':'359'},
            {'acronym':'BH','text':'BH +973','l_text':'BAHRAIN','id':'973'},
            {'acronym':'BI','text':'BI +257','l_text':'BURUNDI','id':'257'},
            {'acronym':'BJ','text':'BJ +229','l_text':'BENIN','id':'229'},
            {'acronym':'BL','text':'BL +590','l_text':'SAINT BARTHELEMY','id':'590'},
            {'acronym':'BM','text':'BM +1441','l_text':'BERMUDA','id':'1441'},
            {'acronym':'BN','text':'BN +673','l_text':'BRUNEI DARUSSALAM','id':'673'},
            {'acronym':'BO','text':'BO +591','l_text':'BOLIVIA','id':'591'},
            {'acronym':'BR','text':'BR +55','l_text':'BRAZIL','id':'55'},
            {'acronym':'BS','text':'BS +1242','l_text':'BAHAMAS','id':'1242'},
            {'acronym':'BT','text':'BT +975','l_text':'BHUTAN','id':'975'},
            {'acronym':'BW','text':'BW +267','l_text':'BOTSWANA','id':'267'},
            {'acronym':'BY','text':'BY +375','l_text':'BELARUS','id':'375'},
            {'acronym':'BZ','text':'BZ +501','l_text':'BELIZE','id':'501'},
            {'acronym':'CA','text':'CA +1','l_text':'CANADA','id':'1'},
            {'acronym':'CC','text':'CC +61','l_text':'COCOS (KEELING) ISLANDS','id':'61'},
            {'acronym':'CD','text':'CD +243','l_text':'CONGO, THE DEMOCRATIC REPUBLIC OF THE','id':'243'},
            {'acronym':'CF','text':'CF +236','l_text':'CENTRAL AFRICAN REPUBLIC','id':'236'},
            {'acronym':'CG','text':'CG +242','l_text':'CONGO','id':'242'},
            {'acronym':'CH','text':'CH +41','l_text':'SWITZERLAND','id':'41'},
            {'acronym':'CI','text':'CI +225','l_text':'COTE D IVOIRE','id':'225'},
            {'acronym':'CK','text':'CK +682','l_text':'COOK ISLANDS','id':'682'},
            {'acronym':'CL','text':'CL +56','l_text':'CHILE','id':'56'},
            {'acronym':'CM','text':'CM +237','l_text':'CAMEROON','id':'237'},
            {'acronym':'CN','text':'CN +86','l_text':'CHINA','id':'86'},
            {'acronym':'CO','text':'CO +57','l_text':'COLOMBIA','id':'57'},
            {'acronym':'CR','text':'CR +506','l_text':'COSTA RICA','id':'506'},
            {'acronym':'CU','text':'CU +53','l_text':'CUBA','id':'53'},
            {'acronym':'CV','text':'CV +238','l_text':'CAPE VERDE','id':'238'},
            {'acronym':'CX','text':'CX +61','l_text':'CHRISTMAS ISLAND','id':'61'},
            {'acronym':'CY','text':'CY +357','l_text':'CYPRUS','id':'357'},
            {'acronym':'CZ','text':'CZ +420','l_text':'CZECH REPUBLIC','id':'420'},
            {'acronym':'DE','text':'DE +49','l_text':'GERMANY','id':'49'},
            {'acronym':'DJ','text':'DJ +253','l_text':'DJIBOUTI','id':'253'},
            {'acronym':'DK','text':'DK +45','l_text':'DENMARK','id':'45'},
            {'acronym':'DM','text':'DM +1767','l_text':'DOMINICA','id':'1767'},
            {'acronym':'DO','text':'DO +1809','l_text':'DOMINICAN REPUBLIC','id':'1809'},
            {'acronym':'DZ','text':'DZ +213','l_text':'ALGERIA','id':'213'},
            {'acronym':'EC','text':'EC +593','l_text':'ECUADOR','id':'593'},
            {'acronym':'EE','text':'EE +372','l_text':'ESTONIA','id':'372'},
            {'acronym':'EG','text':'EG +20','l_text':'EGYPT','id':'20'},
            {'acronym':'ER','text':'ER +291','l_text':'ERITREA','id':'291'},
            {'acronym':'ES','text':'ES +34','l_text':'SPAIN','id':'34'},
            {'acronym':'ET','text':'ET +251','l_text':'ETHIOPIA','id':'251'},
            {'acronym':'FI','text':'FI +358','l_text':'FINLAND','id':'358'},
            {'acronym':'FJ','text':'FJ +679','l_text':'FIJI','id':'679'},
            {'acronym':'FK','text':'FK +500','l_text':'FALKLAND ISLANDS (MALVINAS)','id':'500'},
            {'acronym':'FM','text':'FM +691','l_text':'MICRONESIA, FEDERATED STATES OF','id':'691'},
            {'acronym':'FO','text':'FO +298','l_text':'FAROE ISLANDS','id':'298'},
            {'acronym':'FR','text':'FR +33','l_text':'FRANCE','id':'33'},
            {'acronym':'GA','text':'GA +241','l_text':'GABON','id':'241'},
            {'acronym':'GB','text':'GB +44','l_text':'UNITED KINGDOM','id':'44'},
            {'acronym':'GD','text':'GD +1473','l_text':'GRENADA','id':'1473'},
            {'acronym':'GE','text':'GE +995','l_text':'GEORGIA','id':'995'},
            {'acronym':'GH','text':'GH +233','l_text':'GHANA','id':'233'},
            {'acronym':'GI','text':'GI +350','l_text':'GIBRALTAR','id':'350'},
            {'acronym':'GL','text':'GL +299','l_text':'GREENLAND','id':'299'},
            {'acronym':'GM','text':'GM +220','l_text':'GAMBIA','id':'220'},
            {'acronym':'GN','text':'GN +224','l_text':'GUINEA','id':'224'},
            {'acronym':'GQ','text':'GQ +240','l_text':'EQUATORIAL GUINEA','id':'240'},
            {'acronym':'GR','text':'GR +30','l_text':'GREECE','id':'30'},
            {'acronym':'GT','text':'GT +502','l_text':'GUATEMALA','id':'502'},
            {'acronym':'GU','text':'GU +1671','l_text':'GUAM','id':'1671'},
            {'acronym':'GW','text':'GW +245','l_text':'GUINEA-BISSAU','id':'245'},
            {'acronym':'GY','text':'GY +592','l_text':'GUYANA','id':'592'},
            {'acronym':'HK','text':'HK +852','l_text':'HONG KONG','id':'852'},
            {'acronym':'HN','text':'HN +504','l_text':'HONDURAS','id':'504'},
            {'acronym':'HR','text':'HR +385','l_text':'CROATIA','id':'385'},
            {'acronym':'HT','text':'HT +509','l_text':'HAITI','id':'509'},
            {'acronym':'HU','text':'HU +36','l_text':'HUNGARY','id':'36'},
            {'acronym':'ID','text':'ID +62','l_text':'INDONESIA','id':'62'},
            {'acronym':'IE','text':'IE +353','l_text':'IRELAND','id':'353'},
            {'acronym':'IL','text':'IL +972','l_text':'ISRAEL','id':'972'},
            {'acronym':'IM','text':'IM +44','l_text':'ISLE OF MAN','id':'44'},
            {'acronym':'IN','text':'IN +91','l_text':'INDIA','id':'91'},
            {'acronym':'IQ','text':'IQ +964','l_text':'IRAQ','id':'964'},
            {'acronym':'IR','text':'IR +98','l_text':'IRAN, ISLAMIC REPUBLIC OF','id':'98'},
            {'acronym':'IS','text':'IS +354','l_text':'ICELAND','id':'354'},
            {'acronym':'IT','text':'IT +39','l_text':'ITALY','id':'39'},
            {'acronym':'JM','text':'JM +1876','l_text':'JAMAICA','id':'1876'},
            {'acronym':'JO','text':'JO +962','l_text':'JORDAN','id':'962'},
            {'acronym':'JP','text':'JP +81','l_text':'JAPAN','id':'81'},
            {'acronym':'KE','text':'KE +254','l_text':'KENYA','id':'254'},
            {'acronym':'KG','text':'KG +996','l_text':'KYRGYZSTAN','id':'996'},
            {'acronym':'KH','text':'KH +855','l_text':'CAMBODIA','id':'855'},
            {'acronym':'KI','text':'KI +686','l_text':'KIRIBATI','id':'686'},
            {'acronym':'KM','text':'KM +269','l_text':'COMOROS','id':'269'},
            {'acronym':'KN','text':'KN +1869','l_text':'SAINT KITTS AND NEVIS','id':'1869'},
            {'acronym':'KP','text':'KP +850','l_text':'KOREA DEMOCRATIC PEOPLES REPUBLIC OF','id':'850'},
            {'acronym':'KR','text':'KR +82','l_text':'KOREA REPUBLIC OF','id':'82'},
            {'acronym':'KW','text':'KW +965','l_text':'KUWAIT','id':'965'},
            {'acronym':'KY','text':'KY +1345','l_text':'CAYMAN ISLANDS','id':'1345'},
            {'acronym':'KZ','text':'KZ +7','l_text':'KAZAKSTAN','id':'7'},
            {'acronym':'LA','text':'LA +856','l_text':'LAO PEOPLES DEMOCRATIC REPUBLIC','id':'856'},
            {'acronym':'LB','text':'LB +961','l_text':'LEBANON','id':'961'},
            {'acronym':'LC','text':'LC +1758','l_text':'SAINT LUCIA','id':'1758'},
            {'acronym':'LI','text':'LI +423','l_text':'LIECHTENSTEIN','id':'423'},
            {'acronym':'LK','text':'LK +94','l_text':'SRI LANKA','id':'94'},
            {'acronym':'LR','text':'LR +231','l_text':'LIBERIA','id':'231'},
            {'acronym':'LS','text':'LS +266','l_text':'LESOTHO','id':'266'},
            {'acronym':'LT','text':'LT +370','l_text':'LITHUANIA','id':'370'},
            {'acronym':'LU','text':'LU +352','l_text':'LUXEMBOURG','id':'352'},
            {'acronym':'LV','text':'LV +371','l_text':'LATVIA','id':'371'},
            {'acronym':'LY','text':'LV +218','l_text':'LIBYAN ARAB JAMAHIRIYA','id':'218'},
            {'acronym':'MA','text':'MA +212','l_text':'MOROCCO','id':'212'},
            {'acronym':'MC','text':'MC +377','l_text':'MONACO','id':'377'},
            {'acronym':'MD','text':'MD +373','l_text':'MOLDOVA, REPUBLIC OF','id':'373'},
            {'acronym':'ME','text':'ME +382','l_text':'MONTENEGRO','id':'382'},
            {'acronym':'MF','text':'MF +1599','l_text':'SAINT MARTIN','id':'1599'},
            {'acronym':'MG','text':'MG +261','l_text':'MADAGASCAR','id':'261'},
            {'acronym':'MH','text':'MH +692','l_text':'MARSHALL ISLANDS','id':'692'},
            {'acronym':'MK','text':'MK +389','l_text':'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','id':'389'},
            {'acronym':'ML','text':'ML +223','l_text':'MALI','id':'223'},
            {'acronym':'MM','text':'MM +95','l_text':'MYANMAR','id':'95'},
            {'acronym':'MN','text':'MN +976','l_text':'MONGOLIA','id':'976'},
            {'acronym':'MO','text':'MO +853','l_text':'MACAU','id':'853'},
            {'acronym':'MP','text':'MP +1670','l_text':'NORTHERN MARIANA ISLANDS','id':'1670'},
            {'acronym':'MR','text':'MR +222','l_text':'MAURITANIA','id':'222'},
            {'acronym':'MS','text':'MS +1664','l_text':'MONTSERRAT','id':'1664'},
            {'acronym':'MT','text':'MT +356','l_text':'MALTA','id':'356'},
            {'acronym':'MU','text':'MU +230','l_text':'MAURITIUS','id':'230'},
            {'acronym':'MV','text':'MV +960','l_text':'MALDIVES','id':'960'},
            {'acronym':'MW','text':'MW +265','l_text':'MALAWI','id':'265'},
            {'acronym':'MX','text':'MX +52','l_text':'MEXICO','id':'52'},
            {'acronym':'MY','text':'MY +60','l_text':'MALAYSIA','id':'60'},
            {'acronym':'MZ','text':'MZ +258','l_text':'MOZAMBIQUE','id':'258'},
            {'acronym':'NA','text':'NA +264','l_text':'NAMIBIA','id':'264'},
            {'acronym':'NC','text':'NC +687','l_text':'NEW CALEDONIA','id':'687'},
            {'acronym':'NE','text':'NE +227','l_text':'NIGER','id':'227'},
            {'acronym':'NG','text':'NG +234','l_text':'NIGERIA','id':'234'},
            {'acronym':'NI','text':'NI +505','l_text':'NICARAGUA','id':'505'},
            {'acronym':'NL','text':'NL +31','l_text':'NETHERLANDS','id':'31'},
            {'acronym':'NO','text':'NO +47','l_text':'NORWAY','id':'47'},
            {'acronym':'NP','text':'NP +977','l_text':'NEPAL','id':'977'},
            {'acronym':'NR','text':'NR +674','l_text':'NAURU','id':'674'},
            {'acronym':'NU','text':'NU +683','l_text':'NIUE','id':'683'},
            {'acronym':'NZ','text':'NZ +64','l_text':'NEW ZEALAND','id':'64'},
            {'acronym':'OM','text':'OM +968','l_text':'OMAN','id':'968'},
            {'acronym':'PA','text':'PA +507','l_text':'PANAMA','id':'507'},
            {'acronym':'PE','text':'PE +51','l_text':'PERU','id':'51'},
            {'acronym':'PF','text':'PF +689','l_text':'FRENCH POLYNESIA','id':'689'},
            {'acronym':'PG','text':'PG +675','l_text':'PAPUA NEW GUINEA','id':'675'},
            {'acronym':'PH','text':'PH +63','l_text':'PHILIPPINES','id':'63'},
            {'acronym':'PK','text':'PK +92','l_text':'PAKISTAN','id':'92'},
            {'acronym':'PL','text':'PL +48','l_text':'POLAND','id':'48'},
            {'acronym':'PM','text':'PM +508','l_text':'SAINT PIERRE AND MIQUELON','id':'508'},
            {'acronym':'PN','text':'PN +870','l_text':'PITCAIRN','id':'870'},
            {'acronym':'PR','text':'PR +1','l_text':'PUERTO RICO','id':'1'},
            {'acronym':'PT','text':'PT +351','l_text':'PORTUGAL','id':'351'},
            {'acronym':'PW','text':'PW +680','l_text':'PALAU','id':'680'},
            {'acronym':'PY','text':'PY +595','l_text':'PARAGUAY','id':'595'},
            {'acronym':'QA','text':'QA +974','l_text':'QATAR','id':'974'},
            {'acronym':'RO','text':'RO +40','l_text':'ROMANIA','id':'40'},
            {'acronym':'RS','text':'RS +381','l_text':'SERBIA','id':'381'},
            {'acronym':'RU','text':'RU +7','l_text':'RUSSIAN FEDERATION','id':'7'},
            {'acronym':'RW','text':'RW +250','l_text':'RWANDA','id':'250'},
            {'acronym':'SA','text':'SA +966','l_text':'SAUDI ARABIA','id':'966'},
            {'acronym':'SB','text':'SB +677','l_text':'SOLOMON ISLANDS','id':'677'},
            {'acronym':'SC','text':'SC +248','l_text':'SEYCHELLES','id':'248'},
            {'acronym':'SD','text':'SD +249','l_text':'SUDAN','id':'249'},
            {'acronym':'SE','text':'SE +46','l_text':'SWEDEN','id':'46'},
            {'acronym':'SG','text':'SG +65','l_text':'SINGAPORE','id':'65'},
            {'acronym':'SH','text':'SH +290','l_text':'SAINT HELENA','id':'290'},
            {'acronym':'SI','text':'SI +386','l_text':'SLOVENIA','id':'386'},
            {'acronym':'SK','text':'SK +421','l_text':'SLOVAKIA','id':'421'},
            {'acronym':'SL','text':'SL +232','l_text':'SIERRA LEONE','id':'232'},
            {'acronym':'SM','text':'SM +378','l_text':'SAN MARINO','id':'378'},
            {'acronym':'SN','text':'SN +221','l_text':'SENEGAL','id':'221'},
            {'acronym':'SO','text':'SO +252','l_text':'SOMALIA','id':'252'},
            {'acronym':'SR','text':'SR +597','l_text':'SURINAME','id':'597'},
            {'acronym':'ST','text':'ST +239','l_text':'SAO TOME AND PRINCIPE','id':'239'},
            {'acronym':'SV','text':'SV +503','l_text':'EL SALVADOR','id':'503'},
            {'acronym':'SY','text':'SY +963','l_text':'SYRIAN ARAB REPUBLIC','id':'963'},
            {'acronym':'SZ','text':'SZ +268','l_text':'SWAZILAND','id':'268'},
            {'acronym':'TC','text':'TC +1649','l_text':'TURKS AND CAICOS ISLANDS','id':'1649'},
            {'acronym':'TD','text':'TD +235','l_text':'CHAD','id':'235'},
            {'acronym':'TG','text':'TG +228','l_text':'TOGO','id':'228'},
            {'acronym':'TH','text':'TH +66','l_text':'THAILAND','id':'66'},
            {'acronym':'TJ','text':'TJ +992','l_text':'TAJIKISTAN','id':'992'},
            {'acronym':'TK','text':'TK +690','l_text':'TOKELAU','id':'690'},
            {'acronym':'TL','text':'TL +670','l_text':'TIMOR-LESTE','id':'670'},
            {'acronym':'TM','text':'TM +993','l_text':'TURKMENISTAN','id':'993'},
            {'acronym':'TN','text':'TN +216','l_text':'TUNISIA','id':'216'},
            {'acronym':'TO','text':'TO +676','l_text':'TONGA','id':'676'},
            {'acronym':'TR','text':'TR +90','l_text':'TURKEY','id':'90'},
            {'acronym':'TT','text':'TT +1868','l_text':'TRINIDAD AND TOBAGO','id':'1868'},
            {'acronym':'TV','text':'TV +688','l_text':'TUVALU','id':'688'},
            {'acronym':'TW','text':'TW +886','l_text':'TAIWAN, PROVINCE OF CHINA','id':'886'},
            {'acronym':'TZ','text':'TZ +255','l_text':'TANZANIA, UNITED REPUBLIC OF','id':'255'},
            {'acronym':'UA','text':'UA +380','l_text':'UKRAINE','id':'380'},
            {'acronym':'UG','text':'UG +256','l_text':'UGANDA','id':'256'},
            {'acronym':'US','text':'US +1','l_text':'UNITED STATES','id':'1'},
            {'acronym':'UY','text':'UY +598','l_text':'URUGUAY','id':'598'},
            {'acronym':'UZ','text':'UZ +998','l_text':'UZBEKISTAN','id':'998'},
            {'acronym':'VA','text':'VA +39','l_text':'HOLY SEE (VATICAN CITY STATE)','id':'39'},
            {'acronym':'VC','text':'VC +1784','l_text':'SAINT VINCENT AND THE GRENADINES','id':'1784'},
            {'acronym':'VE','text':'VE +58','l_text':'VENEZUELA','id':'58'},
            {'acronym':'VG','text':'VG +1284','l_text':'VIRGIN ISLANDS, BRITISH','id':'1284'},
            {'acronym':'VI','text':'VI +1340','l_text':'VIRGIN ISLANDS, U.S.','id':'1340'},
            {'acronym':'VN','text':'VN +84','l_text':'VIET NAM','id':'84'},
            {'acronym':'VU','text':'VU +678','l_text':'VANUATU','id':'678'},
            {'acronym':'WF','text':'WF +681','l_text':'WALLIS AND FUTUNA','id':'681'},
            {'acronym':'WS','text':'WS +685','l_text':'SAMOA','id':'685'},
            {'acronym':'XK','text':'XK +381','l_text':'KOSOVO','id':'381'},
            {'acronym':'YE','text':'YE +967','l_text':'YEMEN','id':'967'},
            {'acronym':'YT','text':'YT +262','l_text':'MAYOTTE','id':'262'},
            {'acronym':'ZA','text':'ZA +27','l_text':'SOUTH AFRICA','id':'27'},
            {'acronym':'ZM','text':'ZM +260','l_text':'ZAMBIA','id':'260'},
            {'acronym':'ZW','text':'ZW +263','l_text':'ZIMBABWE','id':'263'}
        ];
        function formatCountry (country) {
          if (!country.id) { return country.text; }
          var country = $(
            '<span class=\""."flag-icon flag-icon-'+ country.acronym.toLowerCase() +' flag-icon-squared\""."></span>' +
            '<span class=\""."flag-text\"".">'+ country.acronym+' +'+ country.id +'</span>'
          );
          return country;
        };
        
        //Assuming you have a select element with name country
        // e.g. <select name='name'></select>
        
        $('#country_codes').select2({
            templateResult: formatCountry,
            data: isoCountries
        });
        $('#country_codes_login').select2({
          templateResult: formatCountry,
          data: isoCountries
      });
    });      
    </script>";
?>