<?php


function getAreaCode($number){
  $countryArray = [
        ['key' => 'AD','name'=>'ANDORRA','code'=>'376'],
        ['key' => 'AE','name'=>'UNITED ARAB EMIRATES','code'=>'971'],
        ['key' => 'AF','name'=>'AFGHANISTAN','code'=>'93'],
        ['key' => 'AG','name'=>'ANTIGUA AND BARBUDA','code'=>'1268'],
        ['key' => 'AI','name'=>'ANGUILLA','code'=>'1264'],
        ['key' => 'AL','name'=>'ALBANIA','code'=>'355'],
        ['key' => 'AM','name'=>'ARMENIA','code'=>'374'],
        ['key' => 'AN','name'=>'NETHERLANDS ANTILLES','code'=>'599'],
        ['key' => 'AO','name'=>'ANGOLA','code'=>'244'],
        ['key' => 'AQ','name'=>'ANTARCTICA','code'=>'672'],
        ['key' => 'AR','name'=>'ARGENTINA','code'=>'54'],
        ['key' => 'AS','name'=>'AMERICAN SAMOA','code'=>'1684'],
        ['key' => 'AT','name'=>'AUSTRIA','code'=>'43'],
        ['key' => 'AU','name'=>'AUSTRALIA','code'=>'61'],
        ['key' => 'AW','name'=>'ARUBA','code'=>'297'],
        ['key' => 'AZ','name'=>'AZERBAIJAN','code'=>'994'],
        ['key' => 'BA','name'=>'BOSNIA AND HERZEGOVINA','code'=>'387'],
        ['key' => 'BB','name'=>'BARBADOS','code'=>'1246'],
        ['key' => 'BD','name'=>'BANGLADESH','code'=>'880'],
        ['key' => 'BE','name'=>'BELGIUM','code'=>'32'],
        ['key' => 'BF','name'=>'BURKINA FASO','code'=>'226'],
        ['key' => 'BG','name'=>'BULGARIA','code'=>'359'],
        ['key' => 'BH','name'=>'BAHRAIN','code'=>'973'],
        ['key' => 'BI','name'=>'BURUNDI','code'=>'257'],
        ['key' => 'BJ','name'=>'BENIN','code'=>'229'],
        ['key' => 'BL','name'=>'SAINT BARTHELEMY','code'=>'590'],
        ['key' => 'BM','name'=>'BERMUDA','code'=>'1441'],
        ['key' => 'BN','name'=>'BRUNEI DARUSSALAM','code'=>'673'],
        ['key' => 'BO','name'=>'BOLIVIA','code'=>'591'],
        ['key' => 'BR','name'=>'BRAZIL','code'=>'55'],
        ['key' => 'BS','name'=>'BAHAMAS','code'=>'1242'],
        ['key' => 'BT','name'=>'BHUTAN','code'=>'975'],
        ['key' => 'BW','name'=>'BOTSWANA','code'=>'267'],
        ['key' => 'BY','name'=>'BELARUS','code'=>'375'],
        ['key' => 'BZ','name'=>'BELIZE','code'=>'501'],
        ['key' => 'CA','name'=>'CANADA','code'=>'1'],
        ['key' => 'CC','name'=>'COCOS (KEELING) ISLANDS','code'=>'61'],
        ['key' => 'CD','name'=>'CONGO, THE DEMOCRATIC REPUBLIC OF THE','code'=>'243'],
        ['key' => 'CF','name'=>'CENTRAL AFRICAN REPUBLIC','code'=>'236'],
        ['key' => 'CG','name'=>'CONGO','code'=>'242'],
        ['key' => 'CH','name'=>'SWITZERLAND','code'=>'41'],
        ['key' => 'CI','name'=>'COTE D IVOIRE','code'=>'225'],
        ['key' => 'CK','name'=>'COOK ISLANDS','code'=>'682'],
        ['key' => 'CL','name'=>'CHILE','code'=>'56'],
        ['key' => 'CM','name'=>'CAMEROON','code'=>'237'],
        ['key' => 'CN','name'=>'CHINA','code'=>'86'],
        ['key' => 'CO','name'=>'COLOMBIA','code'=>'57'],
        ['key' => 'CR','name'=>'COSTA RICA','code'=>'506'],
        ['key' => 'CU','name'=>'CUBA','code'=>'53'],
        ['key' => 'CV','name'=>'CAPE VERDE','code'=>'238'],
        ['key' => 'CX','name'=>'CHRISTMAS ISLAND','code'=>'61'],
        ['key' => 'CY','name'=>'CYPRUS','code'=>'357'],
        ['key' => 'CZ','name'=>'CZECH REPUBLIC','code'=>'420'],
        ['key' => 'DE','name'=>'GERMANY','code'=>'49'],
        ['key' => 'DJ','name'=>'DJIBOUTI','code'=>'253'],
        ['key' => 'DK','name'=>'DENMARK','code'=>'45'],
        ['key' => 'DM','name'=>'DOMINICA','code'=>'1767'],
        ['key' => 'DO','name'=>'DOMINICAN REPUBLIC','code'=>'1809'],
        ['key' => 'DZ','name'=>'ALGERIA','code'=>'213'],
        ['key' => 'EC','name'=>'ECUADOR','code'=>'593'],
        ['key' => 'EE','name'=>'ESTONIA','code'=>'372'],
        ['key' => 'EG','name'=>'EGYPT','code'=>'20'],
        ['key' => 'ER','name'=>'ERITREA','code'=>'291'],
        ['key' => 'ES','name'=>'SPAIN','code'=>'34'],
        ['key' => 'ET','name'=>'ETHIOPIA','code'=>'251'],
        ['key' => 'FI','name'=>'FINLAND','code'=>'358'],
        ['key' => 'FJ','name'=>'FIJI','code'=>'679'],
        ['key' => 'FK','name'=>'FALKLAND ISLANDS (MALVINAS)','code'=>'500'],
        ['key' => 'FM','name'=>'MICRONESIA, FEDERATED STATES OF','code'=>'691'],
        ['key' => 'FO','name'=>'FAROE ISLANDS','code'=>'298'],
        ['key' => 'FR','name'=>'FRANCE','code'=>'33'],
        ['key' => 'GA','name'=>'GABON','code'=>'241'],
        ['key' => 'GB','name'=>'UNITED KINGDOM','code'=>'44'],
        ['key' => 'GD','name'=>'GRENADA','code'=>'1473'],
        ['key' => 'GE','name'=>'GEORGIA','code'=>'995'],
        ['key' => 'GH','name'=>'GHANA','code'=>'233'],
        ['key' => 'GI','name'=>'GIBRALTAR','code'=>'350'],
        ['key' => 'GL','name'=>'GREENLAND','code'=>'299'],
        ['key' => 'GM','name'=>'GAMBIA','code'=>'220'],
        ['key' => 'GN','name'=>'GUINEA','code'=>'224'],
        ['key' => 'GQ','name'=>'EQUATORIAL GUINEA','code'=>'240'],
        ['key' => 'GR','name'=>'GREECE','code'=>'30'],
        ['key' => 'GT','name'=>'GUATEMALA','code'=>'502'],
        ['key' => 'GU','name'=>'GUAM','code'=>'1671'],
        ['key' => 'GW','name'=>'GUINEA-BISSAU','code'=>'245'],
        ['key' => 'GY','name'=>'GUYANA','code'=>'592'],
        ['key' => 'HK','name'=>'HONG KONG','code'=>'852'],
        ['key' => 'HN','name'=>'HONDURAS','code'=>'504'],
        ['key' => 'HR','name'=>'CROATIA','code'=>'385'],
        ['key' => 'HT','name'=>'HAITI','code'=>'509'],
        ['key' => 'HU','name'=>'HUNGARY','code'=>'36'],
        ['key' => 'ID','name'=>'INDONESIA','code'=>'62'],
        ['key' => 'IE','name'=>'IRELAND','code'=>'353'],
        ['key' => 'IL','name'=>'ISRAEL','code'=>'972'],
        ['key' => 'IM','name'=>'ISLE OF MAN','code'=>'44'],
        ['key' => 'IN','name'=>'INDIA','code'=>'91'],
        ['key' => 'IQ','name'=>'IRAQ','code'=>'964'],
        ['key' => 'IR','name'=>'IRAN, ISLAMIC REPUBLIC OF','code'=>'98'],
        ['key' => 'IS','name'=>'ICELAND','code'=>'354'],
        ['key' => 'IT','name'=>'ITALY','code'=>'39'],
        ['key' => 'JM','name'=>'JAMAICA','code'=>'1876'],
        ['key' => 'JO','name'=>'JORDAN','code'=>'962'],
        ['key' => 'JP','name'=>'JAPAN','code'=>'81'],
        ['key' => 'KE','name'=>'KENYA','code'=>'254'],
        ['key' => 'KG','name'=>'KYRGYZSTAN','code'=>'996'],
        ['key' => 'KH','name'=>'CAMBODIA','code'=>'855'],
        ['key' => 'KI','name'=>'KIRIBATI','code'=>'686'],
        ['key' => 'KM','name'=>'COMOROS','code'=>'269'],
        ['key' => 'KN','name'=>'SAINT KITTS AND NEVIS','code'=>'1869'],
        ['key' => 'KP','name'=>'KOREA DEMOCRATIC PEOPLES REPUBLIC OF','code'=>'850'],
        ['key' => 'KR','name'=>'KOREA REPUBLIC OF','code'=>'82'],
        ['key' => 'KW','name'=>'KUWAIT','code'=>'965'],
        ['key' => 'KY','name'=>'CAYMAN ISLANDS','code'=>'1345'],
        ['key' => 'KZ','name'=>'KAZAKSTAN','code'=>'7'],
        ['key' => 'LA','name'=>'LAO PEOPLES DEMOCRATIC REPUBLIC','code'=>'856'],
        ['key' => 'LB','name'=>'LEBANON','code'=>'961'],
        ['key' => 'LC','name'=>'SAINT LUCIA','code'=>'1758'],
        ['key' => 'LI','name'=>'LIECHTENSTEIN','code'=>'423'],
        ['key' => 'LK','name'=>'SRI LANKA','code'=>'94'],
        ['key' => 'LR','name'=>'LIBERIA','code'=>'231'],
        ['key' => 'LS','name'=>'LESOTHO','code'=>'266'],
        ['key' => 'LT','name'=>'LITHUANIA','code'=>'370'],
        ['key' => 'LU','name'=>'LUXEMBOURG','code'=>'352'],
        ['key' => 'LV','name'=>'LATVIA','code'=>'371'],
        ['key' => 'LY','name'=>'LIBYAN ARAB JAMAHIRIYA','code'=>'218'],
        ['key' => 'MA','name'=>'MOROCCO','code'=>'212'],
        ['key' => 'MC','name'=>'MONACO','code'=>'377'],
        ['key' => 'MD','name'=>'MOLDOVA, REPUBLIC OF','code'=>'373'],
        ['key' => 'ME','name'=>'MONTENEGRO','code'=>'382'],
        ['key' => 'MF','name'=>'SAINT MARTIN','code'=>'1599'],
        ['key' => 'MG','name'=>'MADAGASCAR','code'=>'261'],
        ['key' => 'MH','name'=>'MARSHALL ISLANDS','code'=>'692'],
        ['key' => 'MK','name'=>'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','code'=>'389'],
        ['key' => 'ML','name'=>'MALI','code'=>'223'],
        ['key' => 'MM','name'=>'MYANMAR','code'=>'95'],
        ['key' => 'MN','name'=>'MONGOLIA','code'=>'976'],
        ['key' => 'MO','name'=>'MACAU','code'=>'853'],
        ['key' => 'MP','name'=>'NORTHERN MARIANA ISLANDS','code'=>'1670'],
        ['key' => 'MR','name'=>'MAURITANIA','code'=>'222'],
        ['key' => 'MS','name'=>'MONTSERRAT','code'=>'1664'],
        ['key' => 'MT','name'=>'MALTA','code'=>'356'],
        ['key' => 'MU','name'=>'MAURITIUS','code'=>'230'],
        ['key' => 'MV','name'=>'MALDIVES','code'=>'960'],
        ['key' => 'MW','name'=>'MALAWI','code'=>'265'],
        ['key' => 'MX','name'=>'MEXICO','code'=>'52'],
        ['key' => 'MY','name'=>'MALAYSIA','code'=>'60'],
        ['key' => 'MZ','name'=>'MOZAMBIQUE','code'=>'258'],
        ['key' => 'NA','name'=>'NAMIBIA','code'=>'264'],
        ['key' => 'NC','name'=>'NEW CALEDONIA','code'=>'687'],
        ['key' => 'NE','name'=>'NIGER','code'=>'227'],
        ['key' => 'NG','name'=>'NIGERIA','code'=>'234'],
        ['key' => 'NI','name'=>'NICARAGUA','code'=>'505'],
        ['key' => 'NL','name'=>'NETHERLANDS','code'=>'31'],
        ['key' => 'NO','name'=>'NORWAY','code'=>'47'],
        ['key' => 'NP','name'=>'NEPAL','code'=>'977'],
        ['key' => 'NR','name'=>'NAURU','code'=>'674'],
        ['key' => 'NU','name'=>'NIUE','code'=>'683'],
        ['key' => 'NZ','name'=>'NEW ZEALAND','code'=>'64'],
        ['key' => 'OM','name'=>'OMAN','code'=>'968'],
        ['key' => 'PA','name'=>'PANAMA','code'=>'507'],
        ['key' => 'PE','name'=>'PERU','code'=>'51'],
        ['key' => 'PF','name'=>'FRENCH POLYNESIA','code'=>'689'],
        ['key' => 'PG','name'=>'PAPUA NEW GUINEA','code'=>'675'],
        ['key' => 'PH','name'=>'PHILIPPINES','code'=>'63'],
        ['key' => 'PK','name'=>'PAKISTAN','code'=>'92'],
        ['key' => 'PL','name'=>'POLAND','code'=>'48'],
        ['key' => 'PM','name'=>'SAINT PIERRE AND MIQUELON','code'=>'508'],
        ['key' => 'PN','name'=>'PITCAIRN','code'=>'870'],
        ['key' => 'PR','name'=>'PUERTO RICO','code'=>'1'],
        ['key' => 'PT','name'=>'PORTUGAL','code'=>'351'],
        ['key' => 'PW','name'=>'PALAU','code'=>'680'],
        ['key' => 'PY','name'=>'PARAGUAY','code'=>'595'],
        ['key' => 'QA','name'=>'QATAR','code'=>'974'],
        ['key' => 'RO','name'=>'ROMANIA','code'=>'40'],
        ['key' => 'RS','name'=>'SERBIA','code'=>'381'],
        ['key' => 'RU','name'=>'RUSSIAN FEDERATION','code'=>'7'],
        ['key' => 'RW','name'=>'RWANDA','code'=>'250'],
        ['key' => 'SA','name'=>'SAUDI ARABIA','code'=>'966'],
        ['key' => 'SB','name'=>'SOLOMON ISLANDS','code'=>'677'],
        ['key' => 'SC','name'=>'SEYCHELLES','code'=>'248'],
        ['key' => 'SD','name'=>'SUDAN','code'=>'249'],
        ['key' => 'SE','name'=>'SWEDEN','code'=>'46'],
        ['key' => 'SG','name'=>'SINGAPORE','code'=>'65'],
        ['key' => 'SH','name'=>'SAINT HELENA','code'=>'290'],
        ['key' => 'SI','name'=>'SLOVENIA','code'=>'386'],
        ['key' => 'SK','name'=>'SLOVAKIA','code'=>'421'],
        ['key' => 'SL','name'=>'SIERRA LEONE','code'=>'232'],
        ['key' => 'SM','name'=>'SAN MARINO','code'=>'378'],
        ['key' => 'SN','name'=>'SENEGAL','code'=>'221'],
        ['key' => 'SO','name'=>'SOMALIA','code'=>'252'],
        ['key' => 'SR','name'=>'SURINAME','code'=>'597'],
        ['key' => 'ST','name'=>'SAO TOME AND PRINCIPE','code'=>'239'],
        ['key' => 'SV','name'=>'EL SALVADOR','code'=>'503'],
        ['key' => 'SY','name'=>'SYRIAN ARAB REPUBLIC','code'=>'963'],
        ['key' => 'SZ','name'=>'SWAZILAND','code'=>'268'],
        ['key' => 'TC','name'=>'TURKS AND CAICOS ISLANDS','code'=>'1649'],
        ['key' => 'TD','name'=>'CHAD','code'=>'235'],
        ['key' => 'TG','name'=>'TOGO','code'=>'228'],
        ['key' => 'TH','name'=>'THAILAND','code'=>'66'],
        ['key' => 'TJ','name'=>'TAJIKISTAN','code'=>'992'],
        ['key' => 'TK','name'=>'TOKELAU','code'=>'690'],
        ['key' => 'TL','name'=>'TIMOR-LESTE','code'=>'670'],
        ['key' => 'TM','name'=>'TURKMENISTAN','code'=>'993'],
        ['key' => 'TN','name'=>'TUNISIA','code'=>'216'],
        ['key' => 'TO','name'=>'TONGA','code'=>'676'],
        ['key' => 'TR','name'=>'TURKEY','code'=>'90'],
        ['key' => 'TT','name'=>'TRINIDAD AND TOBAGO','code'=>'1868'],
        ['key' => 'TV','name'=>'TUVALU','code'=>'688'],
        ['key' => 'TW','name'=>'TAIWAN, PROVINCE OF CHINA','code'=>'886'],
        ['key' => 'TZ','name'=>'TANZANIA, UNITED REPUBLIC OF','code'=>'255'],
        ['key' => 'UA','name'=>'UKRAINE','code'=>'380'],
        ['key' => 'UG','name'=>'UGANDA','code'=>'256'],
        ['key' => 'US','name'=>'UNITED STATES','code'=>'1'],
        ['key' => 'UY','name'=>'URUGUAY','code'=>'598'],
        ['key' => 'UZ','name'=>'UZBEKISTAN','code'=>'998'],
        ['key' => 'VA','name'=>'HOLY SEE (VATICAN CITY STATE)','code'=>'39'],
        ['key' => 'VC','name'=>'SAINT VINCENT AND THE GRENADINES','code'=>'1784'],
        ['key' => 'VE','name'=>'VENEZUELA','code'=>'58'],
        ['key' => 'VG','name'=>'VIRGIN ISLANDS, BRITISH','code'=>'1284'],
        ['key' => 'VI','name'=>'VIRGIN ISLANDS, U.S.','code'=>'1340'],
        ['key' => 'VN','name'=>'VIET NAM','code'=>'84'],
        ['key' => 'VU','name'=>'VANUATU','code'=>'678'],
        ['key' => 'WF','name'=>'WALLIS AND FUTUNA','code'=>'681'],
        ['key' => 'WS','name'=>'SAMOA','code'=>'685'],
        ['key' => 'XK','name'=>'KOSOVO','code'=>'381'],
        ['key' => 'YE','name'=>'YEMEN','code'=>'967'],
        ['key' => 'YT','name'=>'MAYOTTE','code'=>'262'],
        ['key' => 'ZA','name'=>'SOUTH AFRICA','code'=>'27'],
        ['key' => 'ZM','name'=>'ZAMBIA','code'=>'260'],
        ['key' => 'ZW','name'=>'ZIMBABWE','code'=>'263']
    ];
        if(substr($number, 0,2) == 63){
                return $number; 
        }
        else{
      for($i = 0; $i < count($countryArray); $i++){
                        $area_code = substr($number, 0, strlen($countryArray[$i]['code']));
                  if($area_code == $countryArray[$i]['code']){
                        $num = substr($number, strlen($countryArray[$i]['code']));
                        break;
                  }
      }
        }
  return '62'.$num;
}
 ?>